.TH RLESS 1
.SH NAME
rless \- A pager in rust.
.SH SYNOPSIS
\fBrless\fR path
.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH EXAMPLES
.TP
Running the program
\fB$ rless numbers.txt\fR
.br
TODO

.SH AUTHOR
.P
.RS 2
.nf
Takashi I <mail@takashiidobe.com>
